function [ optimal R2 ] = jet_model_estimate_curvefit(datay, dataskew,  LB, UB, x0)
% [ params fval ] = jet_model_estimate_curvefit(datay, dataskew, SNR, LB UB, x0)
% Estimates the position and width  of frontal jets by fitting the observed
% skewness and a synthetic skewness curve generated by a Monte-Carlo
% process.
% Requires the Optimization Toolbox

numtracks = 1000;
lsq_options = optimset('Display','off','TolFun',1e-5,'TolX',1e-3,'MaxFunEvals',100,'Jacobian','off');
e=exp(1);
maxskew = max(abs(dataskew));

randn_seed=randn(numtracks,1);
while abs(skewness(randn_seed))>0.001
    randn_seed=randn(numtracks,1);
end
[datapar fval] = lsqcurvefit(@gaussian_derivative,x0(1:2),datay,dataskew,...
    LB(1:2),UB(1:2),lsq_options);
datacurve = gaussian_derivative(datapar,datay);

options=psoptimset('Display','off','TolMesh',1e-5,'TolX',1e-3, ...
    'TolFun',1e-5,'CompletePoll','off','CompleteSearch','off');
x0(2) = datapar(2);
LB(2) = x0(2) - 1;
UB(2) = x0(2) + 1;

% [optimal fval]=patternsearch(@simulate_skewness,x0,[],[],[],[],LB,UB,[],options);
optimal = fmincon(@simulate_skewness,x0,[],[],[],[],LB,UB);
% options = optimset('Display','off');
% [optimal fval]=fmincon(@simulate_skewness,x0,[],[],[],[],LB,UB,[],options);
% [residual simcurve] = gensim(optimal);
% plot(datay,simcurve,'r','LineWidth',2)
[residual simskew] = simulate_skewness(optimal);

R2 = sqrt( sum(simskew-dataskew).^2/ (length(dataskew)-3) );

% clf; hold on;
% plot(datay,dataskew,'k-x')
% plot(datay,datacurve,'r--x','LineWidth',2)

% plot(datay,simskew,'LineWidth',2)


    function [residual simskew] = simulate_skewness(parameters)
        
        var = parameters(1);
        center_x0 = parameters(2);
        L = parameters(3);
        SNR = parameters(4);
        
        center_x0 = center_x0+var*randn_seed;
        nl = length(randn_seed);
        %         whos
        track_heights = erf((ones(nl,1)*datay-center_x0*ones(1,length(datay)))/(sqrt(2)*L));
        track_heights = SNR*track_heights + (1-SNR)*randn(size(track_heights));
        simskew = skewness(track_heights);   
        residual = sum( (simskew-dataskew).^2 );
%         [simpar fval] = lsqcurvefit(@gaussian_derivative,x0(1:2),datay,simskew,...
%             LB(1:2),UB(1:2),lsq_options);       
%         residual = sum( (simpar-datapar).^2 );
%         
%         simcurve = gaussian_derivative(simpar,datay);
        
        
    end

    function [ out J ] = gaussian_derivative(params,x)
        
        center = params(2);
        sigma = params(1);
        amp = sigma*sqrt(e)*maxskew;
        exponential = amp*exp(-(x-center).^2/sigma^2*0.5);
        out =  -(x-center)/sigma^2 .* exponential;
        
        if nargout == 2
            
            J(:,2) = exponential/sigma^4 .* ( sigma^2 - (x-center).^2 );
            J(:,1) = -exponential/sigma^5 .* (-2*sigma^2 + (x-center).^2).*(x-center);
            
        end
        
    end

end

