function basinmask = woa09_basinmask(maskfile)

load metrics.mat

geolon=metrics.geolon.data;
geolat=metrics.geolat.data;
wet=logical(metrics.wet.data);
geolonshift = geolon;
geolonshift(geolonshift<0)=geolonshift(geolonshift<0)+360;
[nlon nlat] = size(geolon);

levmask=nc_varget(maskfile,'basin',[0 0 0],[-1 -1 -1]);
levlon = nc_varget(maskfile,'X');
levlat = nc_varget(maskfile,'Y');

basin_names = makenames;
nbasins = length(basin_names);

basinmask.names=basin_names;
basinmask.lon=geolon;
basinmask.lat=geolat;
basinmask.masks=logical(zeros(nbasins,nlon,nlat));


for basidx = 1:nbasins
    
    tempmask = logical(squeeze(sum((round(levmask)==basidx))));
    
    himmask = round(interp2(levlon,levlat,tempmask,geolonshift,geolat));
    himmask(isnan(himmask))=false;
    basinmask.masks(basidx,:,:)=logical(himmask) & wet;
    
    subplot(2,1,1)
    m_proj('Mercator','lon',[0 360],'lat',[-80 80])
    m_pcolor(levlon,levlat,tempmask);shading flat;
    m_coast('patch',[0 0 0]);m_grid;
    title(basin_names(basidx))
    
    subplot(2,1,2)
    m_proj('Mercator','lon',[-280 80],'lat',[-80 80]);
    m_pcolor(geolon,geolat,basinmask.masks(basidx,:,:));shading flat;
    m_coast('patch',[0 0 0]);m_grid;
    pause
    
end

end

function basin_names = makenames( )
basin_names = {...
'Atlantic Ocean',...
'Pacific Ocean',...
'Indian Ocean',...
'Mediterranean Sea',...
'Baltic Sea',...
'Black Sea',...
'Red Sea',...
'Persian Gulf',...
'Hudson Bay',...
'Southern Ocean',...
'Arctic Ocean',...
'Sea of Japan',...
'Kara Sea',...
'Sulu Sea',...
'Baffin Bay',...
'East Mediterranean',...
'West Mediterranean',...
'Sea of Okhotsk',...
'Banda Sea',...
'Caribbean Sea',...
'Andaman Basin',...
'North Caribbean',...
'Gulf of Mexico',...
'Beaufort Sea',...
'South China Sea',...
'Barents Sea',...
'Celebes Sea',...
'Aleutian Basin',...
'Fiji Basin',...
'North American Basin',...
'West European Basin',...
'Southeast Indian Basin',...
'Coral Sea',...
'East Indian Basin',...
'Central Indian Basin',...
'Southwest Atlantic Basin',...
'Southeast Atlantic Basin',...
'Southeast Pacific Basin',...
'Guatemala Basin',...
'East Caroline Basin',...
'Marianas Basin',...
'Philippine Sea',...
'Arabian Sea',...
'Chile Basin',...
'Somali Basin',...
'Mascarene Basin',...
'Crozet Basin',...
'Guinea Basin',...
'Brazil Basin',...
'Argentine Basin',...
'Tasman Sea',...
'Atlantic Indian Basin',...
'Caspian Sea',...
'Sulu Sea II',...
'Venezuela Basin',...
'Bay of Bengal',...
'Java Sea',...
'East Indian Atlantic Basin'};
end
