%% Load the data from himhind_PV.m
load ~/uw-apl/models/HIM/hindcast/hindcast.PV.mat
load metrics
inpath.sigmatheta = '/ltraid3/ashao/uw-apl/models/HIM/hindcast/';
denfiles = dir([inpath.sigmatheta 'sigmatheta*.mat']);
infile.salt = '/ltraid3/ashao/uw-apl/data/offtrac/input/normalyear/salt.hind.nc';
%%
latidx = find(abs(-32.5-metrics.lath.data)<0.1);
longrid = repmat(metrics.geolon.data(latidx,:),[49 1]);
longrid = [longrid wrapTo360(longrid)];
truncidx = 1:640;
longrid = longrid(:,truncidx);
%% PV along 32S
figure(1); clf;
yrange = [0 1500];
startyear = 1947;
lonrange = [30 115];
depthrange = [0 1200];
pvrange = [0 3];
denlevels = [26.4:0.1:26.6 26.8:0.2:27.4];
colormap(flipud(othercolor('BuDRd_12')));

plotcmds = [ 'i = year - startyear;' ...
    'depth = squeeze(hindcast.depth(i,:,latidx,:));depth = [depth depth]; depth=depth(:,truncidx);', ...
    'PV = abs(double(squeeze(hindcast.PV(i,:,latidx,:))));PV = [PV PV]; PV = PV(:,truncidx);', ...
    'contourf(longrid,depth,PV*1e10,0:0.1:3,''LineColor'',''None'');', ...
    'xlim(lonrange);ylim(depthrange);set(gca,''ydir'',''reverse'',''layer'',''top'');' ...    
    'load([inpath.sigmatheta denfiles(i).name]);dens = squeeze(mean(pden(:,:,latidx,:)));' ...
    ' dens = [dens dens]; dens = dens(:,truncidx);' ...
    '[cs v] =contour(longrid,depth,dens-1000,denlevels,''LineColor'',[1 1 1]*0.4);' ...
    'clabel(cs,v,''Color'',[1 1 1]*0.4);' ...
    'cax=colorbar;ylabel(cax,''PV (10^{10} s m^{-1})'');caxis(pvrange);grid on;ylabel(''Depth (m)'');xlabel(''Longitude (^\circE)'');' ...
    'title(num2str(year));' ...
    ];

subplot(3,1,1); hold on; year = 1965; % 1955
eval(plotcmds);

subplot(3,1,2); hold on; year = 1987; % 1955
eval(plotcmds);

subplot(3,1,3); hold on; year = 2007; % 1955
eval(plotcmds);
saveas(gcf,'/ltraid3/ashao/uw-apl/figs/him_hindcasts/I5_samw_1965_1987_2007.eps','epsc')
%% Salinity along 32S
figure(2);clf;
yrange = [0 1500];
startyear = 1947;
lonrange = [30 115];
depthrange = [0 1200];
saltrange = [34.2 35.5];
denlevels = [26.4:0.1:26.6 26.8:0.2:27.4];
colormap(othercolor('BuDRd_12'));

plotcmds = [ 'i = year - startyear;' ...
    'depth = squeeze(hindcast.depth(i,:,latidx,:));depth = [depth depth]; depth=depth(:,truncidx);', ...
    'start4d = [(i-1)*12 0 0 0];count4d = [12 -1 -1 -1];' ...
    'salt = squeeze(mean(nc_varget(infile.salt,''salt'',start4d,count4d)));' ...
    'salt = squeeze(salt(:,latidx,:)); salt = [salt salt]; salt = salt(:,truncidx);' ...
    'contourf(longrid,depth,salt,34:0.1:36,''LineColor'',''None'');', ...
    'xlim(lonrange);ylim(depthrange);' ...    
    'load([inpath.sigmatheta denfiles(i).name]);dens = squeeze(mean(pden(:,:,latidx,:)));' ...
    ' dens = [dens dens]; dens = dens(:,truncidx);' ...
    '[cs v] =contour(longrid,depth,dens-1000,denlevels,''LineColor'',[0.8 0.8 0.8]);' ...
    'clabel(cs,v,''Color'',[0.8 0.8 0.8]);' ...
    'set(gca,''ydir'',''reverse'',''layer'',''top'');' ...
    'cax=colorbar;ylabel(cax,''PV'');caxis(saltrange);grid on;ylabel(''Depth (m)'');xlabel(''Longitude (^\circE)'');' ...
    'colorbar;caxis(saltrange);grid on;title(num2str(year));' ...
    ];

subplot(3,1,1); hold on; year = 1965; % 1955
eval(plotcmds);

subplot(3,1,2); hold on; year = 1987; % 1955
eval(plotcmds);

subplot(3,1,3); hold on; year = 2007; % 1955
eval(plotcmds);
saveas(gcf,'/ltraid3/ashao/uw-apl/figs/him_hindcasts/I5_aaiw_1965_1987_2007.eps','epsc')